# Generated by Django 6.0 on 2026-02-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_agentprofile_supportprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.AlterModelOptions(
            name='supportprofile',
            options={'verbose_name': 'Support Profile', 'verbose_name_plural': 'Support Profiles'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name': 'Ticket Attachment', 'verbose_name_plural': 'Ticket Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
    ]
